### ISSUE TITLE
msvc compile error

### ISSUE THREAD

**Issue by MutexCast** [xiph/rav1e#3438]
**Describe the bug**
When cargo install dioxus-cli, an error occurred during the compilation of rav1e. It seems that Advapi32.lib is not linked correctly.

**To Reproduce**
On Windows 11 pro 24h2 build 26100.4061, Rust was installed using rustup-init.exe with default settings, resulting in the latest stable version with the MSVC backend. The C++ Desktop Development workload was installed via the Visual Studio Installer. Attempting to install dioxus-cli using cargo install dioxus-cli from the system terminal resulted in a compilation error during the compilation of the rav1e dependency.

**Expected behavior**
No error occured.

**Required Information**
Toolchain (if is a build problem):stable-x86_64-windows-msvc
```
$ cargo --version 1.87.0
$ rustc --version  1.87.0
$ nasm --version # if on x86_64. 2.16.03 But is NASM really necessary?
```
Version:
```
$ rav1e --version 0.7.1
```
Operating system: Windows 11 pro 24h2 build 26100.4061 amd64
```
$ uname -a
```

**Console Output**
Please paste the console output below if it is relevant,
<Details>
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\ocean\\AppData\\Local\\Temp\\rustciozmQc\\symbols.o" "<2 object files omitted>" "C:\\Users\\ocean\\AppData\\Local\\Temp\\cargo-installVBygwu\\release\\deps/{libbuilt-a2be9883bb16f95d.rlib,libgit2-4b56b929f051558d.rlib,liburl-61884d9aba783345.rlib,libidna-1cfc7e14c182189b.rlib,libutf8_iter-c94dc76f5a89502e.rlib,libidna_adapter-6151fa825453e103.rlib,libicu_properties-8e58b7562595a006.rlib,libicu_properties_data-d27e857ef7fa3706.rlib,libicu_normalizer-1b51f6580644e3df.rlib,libsmallvec-a2ebe38ffdf66e7c.rlib,libicu_normalizer_data-66f0fade7aba2d78.rlib,libicu_collections-b64d9c12cb924429.rlib,libpotential_utf-3ca8a9d1e0997d80.rlib,libicu_provider-8f8c72083be09889.rlib,libicu_locale_core-0083fbd013fc96df.rlib,libtinystr-385ac9ae2043aa6e.rlib,liblitemap-17e804ed1c8dbbbd.rlib,libwriteable-4f5eb29aba8b779a.rlib,libzerovec-6c8b1141abdfbdb6.rlib,libzerotrie-ffcb635534b50ec4.rlib,libyoke-3dd57cb98c49154a.rlib,libstable_deref_trait-ba10e75ac4b1f1cf.rlib,libzerofrom-9079a5a93aba366a.rlib,libform_urlencoded-632f5fddb1543c8f.rlib,libpercent_encoding-7ac1db0db2aa321d.rlib,liblog-e5fdd383d31e1d62.rlib,liblibgit2_sys-f199750c1e73097e.rlib,liblibz_sys-76bd878ed07e5a61.rlib,liblibc-7d52453d8f721fc3.rlib,libbitflags-e1b1c5c5b332994c.rlib}.rlib" "<sysroot>\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib/{libstd-*,libpanic_unwind-*,libwindows_targets-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libunwind-*,libcfg_if-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib" "winhttp.lib" "rpcrt4.lib" "ole32.lib" "crypt32.lib" "secur32.lib" "legacy_stdio_definitions.lib" "kernel32.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "dbghelp.lib" "/defaultlib:msvcrt" "/NXCOMPAT" "/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\atlmfc\\lib\\x64" "/LIBPATH:C:\\Users\\ocean\\AppData\\Local\\Temp\\cargo-installVBygwu\\release\\build\\libgit2-sys-19d23486b4ae45cd\\out\\build" "/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\atlmfc\\lib\\x64" "/LIBPATH:C:\\Users\\ocean\\AppData\\Local\\Temp\\cargo-installVBygwu\\release\\build\\libz-sys-5a8c51f9a6d64730\\out\\lib" "/LIBPATH:C:\\Users\\ocean\\AppData\\Local\\Temp\\cargo-installVBygwu\\release\\build\\libz-sys-5a8c51f9a6d64730\\out\\lib" "/OUT:C:\\Users\\ocean\\AppData\\Local\\Temp\\cargo-installVBygwu\\release\\build\\rav1e-82883cb348f1e75b\\build_script_build-82883cb348f1e75b.exe" "/OPT:REF,NOICF" "/DEBUG" "/PDBALTPATH:%_PDB%" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\libstd.natvis"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: Creating library C:\Users\ocean\AppData\Local\Temp\cargo-installVBygwu\release\build\rav1e-82883cb348f1e75b\build_script_build-82883cb348f1e75b.lib and object C:\Users\ocean\AppData\Local\Temp\cargo-installVBygwu\release\build\rav1e-82883cb348f1e75b\build_script_build-82883cb348f1e75b.exp␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_OpenProcessToken, referenced in function current_user_sid␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_CheckTokenMembership, referenced in function git_fs_path_owner_is␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_CopySid, referenced in function sid_dup␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_EqualSid, referenced in function git_fs_path_owner_is␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_GetLengthSid, referenced in function sid_dup␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_GetTokenInformation, referenced in function current_user_sid␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_IsValidSid, referenced in function file_owner_sid␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_IsWellKnownSid, referenced in function git_fs_path_owner_is␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-fs_path.o) : error LNK2019: unresolved external symbol __imp_GetNamedSecurityInfoW, referenced in function file_owner_sid␍
          liblibgit2_sys-f199750c1e73097e.rlib(43a19b30e9e69d8f-sysdir.o) : error LNK2019: unresolved external symbol __imp_RegCloseKey, referenced in function lookup_registry_key␍
          liblibgit2_sys-f199750c1e73097e.rlib(43a19b30e9e69d8f-sysdir.o) : error LNK2019: unresolved external symbol __imp_RegOpenKeyExW, referenced in function lookup_registry_key␍
          liblibgit2_sys-f199750c1e73097e.rlib(43a19b30e9e69d8f-sysdir.o) : error LNK2019: unresolved external symbol __imp_RegQueryValueExW, referenced in function lookup_registry_key␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-rand.o) : error LNK2019: unresolved external symbol __imp_CryptAcquireContextA, referenced in function getseed␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-rand.o) : error LNK2019: unresolved external symbol __imp_CryptReleaseContext, referenced in function getseed␍
          liblibgit2_sys-f199750c1e73097e.rlib(f6e81ea219c0b9f3-rand.o) : error LNK2019: unresolved external symbol __imp_CryptGenRandom, referenced in function getseed␍
          C:\Users\ocean\AppData\Local\Temp\cargo-installVBygwu\release\build\rav1e-82883cb348f1e75b\build_script_build-82883cb348f1e75b.exe : fatal error LNK1120: 15 unresolved external commands␍

error: could not compile `rav1e` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dioxus-cli v0.6.3`, intermediate artifacts can be found at `C:\Users\ocean\AppData\Local\Temp\cargo-installVBygwu`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
</Details>

**Comment by MutexCast** [comment]
I don't know what the principle is, but after installing the latest dioxus-cli 0.7 alpha version, rav1e 0.7.1 passed compilation without generating any errors, this issue didn't seem to have any need to be discussed anymore and I decided to close it.

**Comment by pythoneer** [comment]
@MutexCast have you ever found a way to resolve this? I currently need to build dioxus-cli 0.6.3 and i am facing the same problem.

**Comment by pythoneer** [comment]
@MutexCast I can't use 0.7 its incompatible with a PR that is currently open which only works with 0.6 atm which i need to make my project work (i have found a convoluted workaround but 0.7 is not the answer)

https://github.com/DioxusLabs/dioxus/pull/3753

**Comment by MutexCast** [comment]
> [@MutexCast](https://github.com/MutexCast) I can't use 0.7 its incompatible with a PR that is currently open which only works with 0.6 atm which i need to make my project work (i have found a convoluted workaround but 0.7 is not the answer)
> 
> [DioxusLabs/dioxus#3753](https://github.com/DioxusLabs/dioxus/pull/3753)

If you only need dioxus-cli to work properly and don't have to install it through compilation, you can use cargo binstall, which will install it using the binary files downloaded from GitHub

**Comment by donl07** [comment]
I just encountered this issue with the same dioxus-cli version on Windows as well, and that's why I hate building anything on Windows. 
Strange bugs, complicated building process always exist.
