### ISSUE TITLE
Fails to build on 32-bit x86

### ISSUE THREAD

**Issue by jbeich** [xiph/rav1e#1330]
Regressed by #1328, see [error log](https://github.com/xiph/rav1e/files/3249965/rav1e-s20190604.log).

```rust
error[E0433]: failed to resolve: use of undeclared type or module `nasm_rs`
  --> build.rs:41:3
   |
41 |   nasm_rs::compile_library_args(
   |   ^^^^^^^ use of undeclared type or module `nasm_rs`
```
